placeholders:

    view_navButtons_before:
        items:
            log_work_button: ~

    view_content_data_additional_information:
        items:
            task_timelap_section: ~

items:
    log_work_button:
        template: RAOroCrmTimeLapBundle::logWorkButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_task.entity.class%)

    task_timelap_section:
        template: RAOroCrmTimeLapBundle:Task:timeTrackingSection.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_task.entity.class%)
